// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfdnKIxdpY89GNjGs0uiUd51Nu441MSFY',
    appId: '1:593747566344:web:d152b1a761fc9e400d16bd',
    messagingSenderId: '593747566344',
    projectId: 'fracs-space',
    authDomain: 'fracs-space.firebaseapp.com',
    storageBucket: 'fracs-space.appspot.com',
    measurementId: 'G-DW1RF2GY9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJVAgotQ3stqgJHCFHxv-HMS5Sy7KgU5s',
    appId: '1:593747566344:android:590c7ed1ea43fdff0d16bd',
    messagingSenderId: '593747566344',
    projectId: 'fracs-space',
    storageBucket: 'fracs-space.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyCViuJJ8E7v8u5ym3__aBTOkmV3EqqVg',
    appId: '1:593747566344:ios:bc8c1257b977caea0d16bd',
    messagingSenderId: '593747566344',
    projectId: 'fracs-space',
    storageBucket: 'fracs-space.appspot.com',
    iosBundleId: 'com.example.fracsSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyCViuJJ8E7v8u5ym3__aBTOkmV3EqqVg',
    appId: '1:593747566344:ios:fb00fc687b32367c0d16bd',
    messagingSenderId: '593747566344',
    projectId: 'fracs-space',
    storageBucket: 'fracs-space.appspot.com',
    iosBundleId: 'com.example.fracsSpace.RunnerTests',
  );
}
